Use GraphQL to get a per-user query to speed things up
Eilon/Hubbup pull request #98
Opened 2017-06-05 18:47 UTC by anurse

I haven't been able to get the full feature set ported to this faster querying model, and continuing to port seems to be drilling kinda deep into some GitHub fiddling that doesn't get us much new info on the ASP.NET Platform side. So, what I've done is kept the legacy pages available via a link on the repo set page:

![image](https://cloud.githubusercontent.com/assets/7574/26798072/18f8f460-49e4-11e7-9f86-812cd1e22c51.png)

I also wasn't able to port the `ItemsAssignedToPersonSet` inclusion level to GraphQL, but I'm not sure it's that useful since all it would do is hide PRs created by the user but not assigned to them, which is actually a common practice in our repos.

We'll need to talk about deployment. There's a corresponding PR coming for the Hubbup data to add the "person set" data, which was previously defined in code.

/cc @Eilon @muratg

2017-06-06 22:58 UTC, anurse commented
:up: :date:

* Moved stand-up view to `/[repoSetName]`
* Reverted config key rename
* Added display of number of pages of data fetch (to help diagnose sudden rate limit cost changes)

2017-06-07 16:23 UTC, anurse commented
@Eilon this should now be at the state we discussed earlier, everything except the change to React/Redux is done. I'm going to start that change in a new branch on top of this, but the sooner we can get this merged, the better :)

2017-06-08 17:10 UTC, Eilon requested changes
A few scattered comments, nothing major I think. Looks very good!!!

2017-06-08 17:10 UTC, Eilon commented on NuGet.config
> +        <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
Why is the .NET feed needed? Doesn't the ASP.NET Core feed have everything mirrored?

2017-06-08 17:10 UTC, Eilon commented on src/Hubbup.Web/Controllers/ApiController.cs
> +    public class ApiController : Controller
Maybe give this a controller/route a more specific name?

2017-06-08 17:10 UTC, Eilon commented on src/Hubbup.Web/Controllers/ApiController.cs
> +        [Route("groups/{groupName}/issues/{userName}")]
Can all the "groups" stuff be renamed to "reposet"? That's the terminology that's already used everywhere.

2017-06-08 17:10 UTC, Eilon commented on src/Hubbup.Web/Controllers/IssueListController.cs
> -        public TelemetryClient TelemetryClient { get; }
Why is the telemetry gone 😢

2017-06-08 17:10 UTC, Eilon commented on src/Hubbup.Web/DataSources/DataLoadingService.cs
> +        private int _loading = 0;
0's the default!

2017-06-08 17:10 UTC, Eilon commented on src/Hubbup.Web/DataSources/GitHubDataSource.cs
> +        private const string GraphQlEndPoint = "https://api.github.com/graphql";
`Endpoint` is one word!

2017-06-08 17:10 UTC, Eilon commented on src/Hubbup.Web/Pages/Index.cshtml
> +                <div class="pull-right small">
Would be nice to just put this at the bottom of the page. I don't think it's necessary to show the rate limit everywhere?

2017-06-08 17:10 UTC, Eilon commented on src/Hubbup.Web/Pages/Index.cshtml
> +            <div class="alert alert-info">Not working on any Issues</div>
Should keep the old text:

`Not working on any assigned issues`

2017-06-08 17:10 UTC, Eilon commented on src/Hubbup.Web/Pages/Index.cshtml
> +            <div class="alert alert-info">Not working on any Pull Requests</div>
Old text:

`No pull requests created or assigned`

2017-06-08 17:10 UTC, Eilon commented on src/Hubbup.Web/Pages/Index.cshtml
> +            <div class="alert alert-info">No other Issues assigned</div>
`No other assigned issues`

2017-06-08 17:10 UTC, Eilon commented on src/Hubbup.Web/Pages/Index.cshtml
> +            else if(remaining < 2000) {
Space after `if`! 😄

2017-06-08 17:10 UTC, Eilon commented on src/Hubbup.Web/Startup.cs
> +            services.AddMemoryCache();
Maybe not actually needed? I would think AddMvc probably adds this anyway.

2017-06-08 17:10 UTC, Eilon commented on src/Hubbup.Web/Views/IssueList/Index.cshtml
> +        <a asp-page="/Index" asp-route-groupName="@Model.RepoSetName">Switch to the new fastness</a>
😁

2017-06-08 17:10 UTC, Eilon commented on src/Hubbup.Web/Views/Shared/_Layout.cshtml
> +    <!DOCTYPE html>
Unindent all this??

2017-06-08 17:10 UTC, Eilon commented on src/Hubbup.Web/DataSources/LocalJsonDataSource.cs
> +            if(etag != null && DateTime.TryParseExact(etag, "O", CultureInfo.InvariantCulture, DateTimeStyles.AdjustToUniversal, out var date))
Formatting: space after `if`!

2017-06-08 17:10 UTC, Eilon commented on src/Hubbup.Web/DataSources/LocalJsonDataSource.cs
> +                if(File.GetLastWriteTimeUtc(path) <= date)
And here!

2017-06-08 17:10 UTC, Eilon commented on src/Hubbup.Web/bundleconfig.json
> +﻿// Configure bundling and minification for the project.
Is this file even used?

2017-06-08 18:30 UTC, anurse commented on src/Hubbup.Web/DataSources/DataLoadingService.cs
> +        private int _loading = 0;
I generally dislike implicit defaults, but I know we use them consistently in other stuff so I'll fix it.

2017-06-08 18:31 UTC, anurse commented on src/Hubbup.Web/DataSources/GitHubDataSource.cs
> +        private const string GraphQlEndPoint = "https://api.github.com/graphql";
Tell that to [System.Net.EndPoint](https://msdn.microsoft.com/en-us/library/system.net.endpoint(v=vs.110).aspx) ;). I'll fix it anyway though.

2017-06-08 18:33 UTC, anurse commented on src/Hubbup.Web/Pages/Index.cshtml
> +            else if(remaining < 2000) {
These are a particular pain because I can't reformat because of https://github.com/aspnet/Razor/issues/1394

2017-06-08 18:36 UTC, anurse commented on src/Hubbup.Web/Views/Shared/_Layout.cshtml
> +    <!DOCTYPE html>
https://github.com/aspnet/Razor/issues/1394 strikes again :)

2017-06-08 18:37 UTC, anurse commented on src/Hubbup.Web/bundleconfig.json
> +﻿// Configure bundling and minification for the project.
No idea, it was here before and I don't know what it's used for ;). I'll try removing it.

2017-06-08 18:37 UTC, anurse commented on NuGet.config
> +        <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
It's not, and I'm pretty sure Octokit CI isn't needed either.

2017-06-08 18:38 UTC, anurse commented on src/Hubbup.Web/Pages/Index.cshtml
> +                <div class="pull-right small">
Moving it. Also going to remove the rate limit badges from the user frames in non-Development environments. They're really useful when developing to see the rate limit impact of each load, but just noise in "Production"

2017-06-08 19:30 UTC, Eilon commented on src/Hubbup.Web/DataSources/DataLoadingService.cs
> +        private int _loading = 0;
Well you didn't set all the ref fields to null 😄

2017-06-08 19:33 UTC, Eilon commented on src/Hubbup.Web/bundleconfig.json
> +﻿// Configure bundling and minification for the project.
It's a file that you have to opt-in to using if you install the bundler/minifier... but I don't know that people do. I don't 😄

2017-06-08 19:42 UTC, Eilon approved these changes

2017-06-08 19:42 UTC, merged